name: ili_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pathlib
  - pyaml
  - pytorch
  - pytorch-lightning
  - xarray
  - seaborn
  - cython
  - pip:
      - pylians
      - sbi
