
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNPE'
  name: 'toy_SNPE'
  nets:
    - model: 'maf'
      hidden_features: 64 
      num_transforms: 6
    - model: 'maf'
      hidden_features: 64 
      num_transforms: 6
    
train_args:
  training_batch_size: 32
  learning_rate: 0.0001
  num_round: 2  # number of rounds of simulations

device: 'cpu'
output_path: './toy'
