
prior:
  module: 'ili.utils'
  class: 'IndependentNormal'
  args:
    loc: [0,0,0]
    scale: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNPE'
  name: 'toy_SNPE'
  nets:
    - model: 'maf'
      hidden_features: 64 
      num_transforms: 6
    - model: 'maf'
      hidden_features: 64 
      num_transforms: 6
    # - model: 'mdn'
    #   hidden_features: 64 
    #   num_components: 5
    
train_args:
  training_batch_size: 32
  learning_rate: 0.00001
  num_round: 5  # number of rounds of simulations

device: 'cpu'
output_path: './toy'
