
prior:
  module: 'ili.utils'
  class: 'IndependentNormal'
  args:
    loc: [14.2]
    scale: [1]

embedding_net:
  module: 'ili.embedding'
  class: 'CNN'
  args:
    in_shape: [1, 128, 128]
    n_channels: [8, 16, 32, 32]
    kernel_sizes: [6, 6, 6, 6]
    strides: [2, 2, 1, 1]
    pool_sizes: [2, 2]
    n_hiddens: [64, 64, 32]


model:
  module: 'sbi.inference'
  class: 'SNPE'
  name: 'xray_SNPE'
  nets:
    - model: 'maf'
      hidden_features: 32 
      num_transforms: 3
    - model: 'mdn'
      hidden_features: 32 
      num_components: 3
    
train_args:
  training_batch_size: 32
  learning_rate: 0.0005

device: 'cuda'
output_path: './xray'
