
prior:
  module: 'sbi.utils'
  class: 'BoxUniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

embedding_net:
  module: 'ili.embedding'
  class: 'FCN'
  args:
    n_summary: 10
    n_hidden: [64,64]
    act_fn: "SiLU"

model:
  module: 'sbi.inference'
  class: 'SNPE'
  name: 'toy_SNPE'
  nets:
    - model: 'maf'
      hidden_features: 50 
      num_transforms: 5
    - model: 'mdn'
      hidden_features: 50 
      num_components: 6
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
