
prior:
  module: 'ili.utils'
  class: 'IndependentNormal'
  args:
    loc: [0,0,0]
    scale: [1,1,1]

embedding_net:
  module: 'ili.embedding'
  class: 'FCN'
  args:
    n_data: 10
    n_hidden: [64,64]
    act_fn: "ReLU"

model:
  module: 'sbi.inference'
  class: 'SNPE'
  name: 'toy_SNPE'
  nets:
    - model: 'maf'
      hidden_features: 64 
      num_transforms: 6
    - model: 'mdn'
      hidden_features: 64 
      num_components: 6
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
