
prior:
  module: 'torch.distributions'
  class: 'Normal'
  args:
    loc: [0,0,0]
    scale: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNLE'
  name: 'toy_SNLE'
  nets:
    - model: 'maf'
      hidden_features: 64 
      num_transforms: 6
    - model: 'mdn'
      hidden_features: 64 
      num_components: 6
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
