backend: 'sbi'

posterior_path: './toy/toy_SNLE_posterior.pkl'
output_path: './toy'
labels: ['t1', 't2', 't3']

ensemble_mode: True

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      seed: 123
      save_samples: True
      num_samples: 1500
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: 6
        burn_in: 100
        thin: 10

  # coverages:
  #   module: 'ili.validation.metrics'
  #   class: 'PosteriorCoverage'
  #   args:
  #     num_samples: 100
  #     sample_method: 'slice_np_vectorized'
  #     sample_params:
  #       num_chains: -1
  #       burn_in: 20
  #       thin: 1
  #     plot_list: ["coverage", "histogram", "predictions", "tarp"]


  # samples:
  #   module: 'ili.validation.metrics'
  #   class: 'PosteriorSamples'
  #   args:
  #     num_samples: 100
  #     sample_method: 'slice_np_vectorized'
  #     sample_params:
  #       num_chains: -1
  #       burn_in: 20
  #       thin: 1
