
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    lower: [0.1, 0.5, 0.6]
    upper: [0.5, 0.9, 1.0]

model:
  backend: 'pydelfi'
  engine: 'NLE'  # Neural Likelihood Estimation
  name: 'quijote_pydelfi'
  nets:
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 50
      num_transforms: 5 
      signature: "maf"
    
train_args:
  batch_size: 32
  epochs: 100

out_dir: 'toy'
