
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    lower: [0.1, 0.5, 0.6]
    upper: [0.5, 0.9, 1.0]

model:
  backend: 'pydelfi'
  engine: 'NLE'  # Neural Likelihood Estimation
  name: 'quijote_pydelfi'
  nets:
    - module: 'pydelfi.ndes'
      class: 'ConditionalMaskedAutoregressiveFlow'
      args: 
        n_hiddens: [50,50]
        n_mades: 5
        act_fun: 'tanh'
    
train_args:
  batch_size: 32
  epochs: 100

out_dir: 'toy'
