
prior:
  module: 'sbi.utils'
  class: 'BoxUniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNPE_C'
  str_save: "toy_mr_"
  nets:
    - model: 'maf'
      hidden_features: 100 
      num_transforms: 2
      signature: "maf_mr_"
    - model: 'mdn'
      hidden_features: 50 
      num_components: 4
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001
  num_round: 2

device: 'cpu'
output_path: './toy'
