
# Specify prior
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

# Specify the inference model
model:
  backend: 'pydelfi'
  engine: 'NLE'  # Neural Likelihood Estimation
  name: 'toy_pydelfi'
  nets:
    - module: 'pydelfi.ndes'
      class: 'MixtureDensityNetwork'
      args: 
        n_components: 12
        n_hidden: [64,64]
        activations: ['tanh','tanh']
    - module: 'pydelfi.ndes'
      class: 'ConditionalMaskedAutoregressiveFlow'
      args: 
        n_hiddens: [50,50]
        n_mades: 2
        act_fun: 'tanh'

# Specify the neural training hyperparameters
train_args:
  batch_size: 32
  epochs: 300

out_dir: 'toy'  # Where to save the posterior
