
# Specify prior
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

# Specify the inference model
model:
  backend: 'pydelfi'
  engine: 'NLE'  # Neural Likelihood Estimation
  name: 'toy_pydelfi'
  nets:
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 50
      num_transforms: 5 
      signature: "maf"
    - model: 'mdn'  # Mixture Density Network
      hidden_features: 50 
      num_components: 6

# Specify the neural training hyperparameters
train_args:
  batch_size: 32
  epochs: 300

out_dir: 'toy'  # Where to save the posterior
