
prior:
  module: 'sbi.utils'
  class: 'BoxUniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNPE'
  str_save: 'new_toy_SNPE_'
  nets:
    - model: 'maf'
      hidden_features: 50 
      num_transforms: 5
      signature: "test_sig_maf_"
    - model: 'mdn'
      hidden_features: 50 
      num_components: 6
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
