backend: 'sbi'

posterior_path: 'toy/posterior.pkl'
output_path: 'toy'
labels: [ 'Omega_m', 'h', 'sigma_8' ]

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 100

  coverages:
    module: 'ili.validation.metrics'
    class: 'PosteriorCoverage'
    args:
      num_samples: 200
      sample_method: 'direct'
      plot_list: ["coverage", "histogram", "predictions", "tarp"]
