meta_path: './toy/quijote_pydelfi_posterior.pkl'
output_path: 'toy'
labels: [ 'Omega_m', 'h', 'sigma_8' ]

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1000
      sample_method: 'emcee'  # MCMC slice sampling (emcee backend)
      sample_params:
        num_chains: 10
        burn_in: 100
        thin: 10
