backend: 'sbi'

posterior_path: './toy/new_PR_posterior.pkl'
output_path: './toy'
labels: ['t1', 't2', 't3']

ensemble_mode: False

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1200
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: -1
        burn_in: 100
        thin: 10

  coverages:
    module: 'ili.validation.metrics'
    class: 'PosteriorCoverage'
    args:
      num_samples: 10
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: -1
        burn_in: 20
        thin: 1
      plot_list: ["coverage", "histogram", "predictions", "TARP"]


  samples:
    module: 'ili.validation.metrics'
    class: 'PosteriorSamples'
    args:
      num_samples: 3
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: -1
        burn_in: 20
        thin: 1
