posterior_file: 'toy_SNPE_posterior.pkl'
out_dir: './toy'
style_path: './style.mcstyle'  # Optional matplotlib style file
labels: ['t1', 't2', 't3']

ensemble_mode: True

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1200
      sample_method: 'direct'
