loader:
  module: 'ili.inference.loaders'
  class: 'SummarizerDatasetLoader'
  args:
    num_nodes: 2000
    in_dir: '/Users/matthewho/git/ltu-ili/data/quijote'
    root_file: 'tpcf/z_0.50/quijote'
    param_file: 'latin_hypercube_params.txt'
    param_names: ['Omega_m', 'h', 'sigma_8']

posterior_path: 'toy/posterior.pkl'
output_path: 'toy'

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1000
      labels: [ 'Omega_m', 'h', 'sigma_8' ]

  rank_stats:
    module: 'ili.validation.metrics'
    class: 'PlotRankStatistics'
    args:
      num_samples: 1000
      labels: [ 'Omega_m', 'h', 'sigma_8' ]